name: Preview build on PR
on:
  pull_request:
    branches: ['main']
jobs:
  build_ios:
    name: Preview iOS
    type: build
    params:
      platform: ios
      profile: preview
  build_android:
    name: Preview Android
    type: build
    params:
      platform: android
      profile: preview
