name: Production build on master
on:
  push:
    branches: ['main']
jobs:
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
  submit_ios:
    name: Submit iOS to App Store Connect
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      profile: production
      build_id: ${{ needs.build_ios.outputs.build_id }}
